name: tstore_ecommerce_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  # Custom Packages
  t_utils: ^0.0.4


  # Utility Packages
  gap: ^3.0.1
  dio: ^5.9.0
  uuid: ^4.5.2
  http: ^1.6.0
  intl: ^0.20.2
  lottie: ^3.3.1 # OR RIVE
  shimmer: ^3.0.0
  logger: ^2.6.2
  flutter_quill: ^11.5.0
  flutter_svg: ^2.2.2
  image_picker: ^1.2.1
  image_cropper: ^11.0.0
  url_launcher: ^6.3.2
  connectivity_plus: ^6.1.2
  cached_network_image: ^3.4.1
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.2.1
  country_code_picker: ^3.4.1
  otp_text_field: ^1.1.3
  animate_do: ^4.2.0
  badges: ^3.1.2
  wakelock_plus: ^1.4.0 #Only being used in the Dummy Data Uploader to keep screen on.
  change_app_package_name: ^1.4.0


  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  # State Management
  get: ^4.7.2
  get_storage: ^2.1.1

  # Product Specific
  readmore: ^3.0.0
  carousel_slider: ^5.1.1
  flutter_rating_bar: ^4.0.1
  capped_progress_indicator: ^0.0.2

  # Firebase
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  firebase_messaging: ^16.0.4
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4
  google_sign_in: ^6.2.2
  cloud_functions: ^6.0.4
  firebase_crashlytics: ^5.0.4

  # Notification
  flutter_local_notifications: ^19.5.0

  # Chat
  audioplayers: ^6.5.1
  audio_waveforms: ^1.3.0
  flutter_chat_ui: ^1.6.15
  flutter_chat_types: ^3.6.2
  path_provider: ^2.1.5


  # Payment
  flutter_paypal: ^0.2.1
  flutter_stripe: ^11.5.0
  razorpay_flutter: ^1.4.0
  midtrans_sdk: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

# Dependency override because of midtrans_snap package as it is using 0.19.0
dependency_overrides:
  intl: ^0.20.2


# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true


  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/logos/
    - assets/language/
    - assets/icons/brands/
    - assets/images/content/
    - assets/images/banners/
    - assets/images/reviews/
    - assets/images/products/
    - assets/icons/categories/
    - assets/images/animations/
    - assets/icons/payment_methods/
    - assets/images/on_boarding_images/

  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800